DECLARE
      CURSOR BK IS
      SELECT *
      FROM BOOK
      WHERE PRICE >500;

      HH BK%ROWTYPE;

BEGIN
    OPEN BK;
    LOOP
       FETCH BK INTO HH;
       EXIT WHEN BK%NOTFOUND;

      DBMS_OUTPUT.PUT_LINE('ID : ' || HH.BOOK_ID );
      DBMS_OUTPUT.PUT_LINE('TITLE : ' || HH.TITLE );
      DBMS_OUTPUT.PUT_LINE('PRICE : ' || HH.PRICE );
      DBMS_OUTPUT.PUT_LINE('AUTHOR : ' || HH.AUTHOR );
      DBMS_OUTPUT.PUT_LINE('PUBLISHER : ' || HH.PUBLISHER);

   END LOOP;
   CLOSE BK;
   
END;
