CREATE TABLE  "BOOK" 
   (	"BOOK_ID" VARCHAR2(30), 
	"TITLE" VARCHAR2(30), 
	"PRICE" NUMBER, 
	"AUTHOR" VARCHAR2(30), 
	"PUBLISHER" VARCHAR2(30), 
	 CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX  ENABLE
   )
/


CREATE TABLE  "USERS" 
   (	"USER_ID" VARCHAR2(30), 
	"USERNAME" VARCHAR2(30), 
	"PASSWORD" VARCHAR2(30), 
	"UTYPE" VARCHAR2(30), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "BOOK_REVIEW" 
   (	"R_ID" VARCHAR2(30), 
	"REVIEWS" VARCHAR2(30), 
	"USER_ID" VARCHAR2(30), 
	"BOOK_ID" VARCHAR2(30), 
	"COMMENTS" VARCHAR2(50), 
	 CONSTRAINT "BOOK_REVIEW_PK" PRIMARY KEY ("R_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "BOOK_REVIEW" ADD CONSTRAINT "BOOK_REVIEW_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
/
ALTER TABLE  "BOOK_REVIEW" ADD CONSTRAINT "BOOK_REVIEW_FK1" FOREIGN KEY ("BOOK_ID")
	  REFERENCES  "BOOK" ("BOOK_ID") ENABLE
/
